name: Sync to Gitee

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: gitee
    steps:
      - name: Mirror to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/fliaping
          dst: gitee/fliaping
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "agent-workspace"
          force_update: true
          account_type: user
